import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

export default function Home() {
  return (
    <>
      <Navbar></Navbar>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <Link href="https://nextjs.org">Next.js!</Link>
          </h1>
        </main>
      </div>
      <Footer></Footer>
    </>
  );
}
